### ISSUE TITLE
Fix pthread

### ISSUE THREAD

**Issue by qianxichen233** [Lind-Project/lind-wasm#32]
Currently pthread is using clone_syscall, which is implemented using Asyncify. There is an issue on current approach using Asyncify to implement pthread (i.e. unwind/rewind two wasm within same memory at the same time): The variable to control the unwind/rewind state is a global variable that is shared by parent and child threads, which means they will compete for the unwind/rewind state. I am actually pretty surprised that the pthread could work kind stably without triggering the issue previously, until I finally observed the issue.
To resolve the issue might be a little tricky, there are several ways I currently can think of to resolve the issue:
1. Try to syncronize the parent and child thread on asyncify state (i.e. use barrier to make parent and child always at the same asyncify step). This may add additional overhead on pthread creation and could still potentially have issues on other aspects.
2. Try to make the asyncify state global variable be non-shared for parent and child: create a non-shared memory region for threading that is used to store some per-thread global variables and make the asyncify state global variable sits in there. Since we now have vmmap, this approach shouldn't be hard to implement, but I am not sure if that aligns with our memory management architecture.
3. Fallback to wasi-thead implementation of pthread

**Comment by rennergade** [comment]
Let's also fix epoch interruption to work with multi-processing here. Should be able to give us much more control for exiting.

**Comment by rennergade** [comment]
Closing this issue and creating a separate issue for epoch_interruption.
